/**********************************************************************

	--- Qt Architect generated file ---

	File: serverchanneldata.h
	Last generated: Sat Jan 17 19:44:55 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef serverchanneldata_included
#define serverchanneldata_included

#include <qframe.h>
#include <qpushbt.h>
#include <qlined.h>
#include <qlistbox.h>

class serverchanneldata : public QFrame
{
    Q_OBJECT

public:

    serverchanneldata
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~serverchanneldata();

public slots:


protected slots:

    virtual void servers_delete();
    // [KDE1 Revival 2026] 槽签名 TQString 化：与 textChanged(const TQString&) 连接匹配
    virtual void servers_sle_update(const TQString&);
    virtual void channels_delete();
    virtual void channels_sle_update(const TQString&);
    virtual void servers_add();
    virtual void channels_add();

protected:
    QListBox* LB_Servers;
    QListBox* LB_Channels;
    QPushButton* B_AddChannels;
    QPushButton* B_AddServers;
    QLineEdit* SLE_Servers;
    QLineEdit* SLE_Channels;

};

#endif // serverchanneldata_included
