/**********************************************************************

	--- Dlgedit generated file ---

	File: FontsData.h
	Last generated: Tue Jun 24 22:20:39 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef FontsData_included
#define FontsData_included

#include <qdialog.h>
#include <qcombo.h>
#include <qlined.h>

#include "Data.h"

class FontsData : public QDialog
{
    Q_OBJECT

public:

    FontsData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~FontsData();

    Data* data;

public slots:


protected slots:

    // [KDE1 Revival 2026] 槽签名 TQt3 化：组合框槽收 int、行编辑槽收 TQString（匹配原生信号）
    virtual void SymbolSetComboSelected(int);
    virtual void LanguageComboBoxSelected(int);
    virtual void Fontnumberselected(const TQString&);
    virtual void Pitchselected(const TQString&);
    virtual void PointSizeselected(const TQString&);

protected:
    QComboBox* LanguageComboBox;
    QComboBox* SymbolSetCombo;
    QLineEdit* Font;
    QLineEdit* Pitch;
    QLineEdit* PointSize;

};

#endif // FontsData_included
