.TH "tqtconfig" "1" "3.0.3" "Troll Tech AS, Norway." ""
.SH "NAME"
.LP 
tqtconfig \- Configuration tool for TQt
.SH "DESCRIPTION"
.LP 
TQtConfig allows for GUI based configuration of TQt and
 other TQt based sources.

.SH "ENVIRONMENT VARIABLES"
.LP 
.TP 
\fBTQTDIR\fP
Specifies the base TQt dir
.SH "AUTHORS"
.LP 
TrollTech <http://www.trolltech.com/>
