/****************************************************************************
**
** TQt GUI Toolkit
**
** This header file efficiently includes all TQt GUI Toolkit functionality.
**
** Generated : Mon Oct 13 13:07:29 CEST 2003

**
** Copyright (C) 1995-2008 Trolltech ASA.  All rights reserved.
**
** This file is part of the TQt GUI Toolkit.
**
*****************************************************************************/

#ifndef QT_H
#define QT_H
#include "ntqglobal.h"
#include "ntqfeatures.h"
#include "ntqshared.h"
#include "ntqptrcollection.h"
#include "ntqglist.h"
#include "ntqobjectdefs.h"
#include "ntqnamespace.h"
#include "ntqgarray.h"
#include "ntqmemarray.h"
#include "ntqcstring.h"
#include "ntqstring.h"
#include "ntqptrlist.h"
#include "ntqiodevice.h"
#include "ntqkeysequence.h"
#include "ntqwindowdefs.h"
#include "ntqgdict.h"
#include "ntqfont.h"
#include "ntqdatastream.h"
#include "ntqpair.h"
#include "ntqpoint.h"
#include <stdio.h>
#include "ntqtextstream.h"
#include "ntqfontinfo.h"
#include "ntqsizepolicy.h"
#include "ntqtl.h"
#include "ntqsize.h"
#include "ntqrect.h"
#include "ntqbitarray.h"
#include "ntqregion.h"
#include "ntqsql.h"
#include "ntqstrlist.h"
#include "ntqvaluelist.h"
#include "ntqmap.h"
#include "ntqdatetime.h"
#include "ntqmime.h"
#include "ntqasciidict.h"
#include "ntqpaintdevice.h"
#include "ntqfontmetrics.h"
#include "ntqdict.h"
#include "ntqevent.h"
#include "ntqhostaddress.h"
#include "ntqstringlist.h"
#include "ntqcolor.h"
#include <ntqdom.h>
#include "ntqobject.h"
#include <ntqdrawutil.h>
#include "ntqbrush.h"
#include "ntqpalette.h"
#include "ntqwidget.h"
#include "ntqjpunicode.h"
#include "ntqtextcodec.h"
#include "ntqpixmap.h"
#include <ntqtabbar.h>
#include "ntqiconset.h"
#include "ntqbutton.h"
#include <ntqtoolbutton.h>
#include "ntqstyle.h"
#include "ntqframe.h"
#include "ntqfile.h"
#include "ntqfileinfo.h"
#include "ntqurlinfo.h"
#include "ntqwidgetlist.h"
#include <ntqcombobox.h>
#include "ntqgroupbox.h"
#include "ntqdialog.h"
#include <ntqdataview.h>
#include "ntqdockwindow.h"
#include "ntqcommonstyle.h"
#include "ntqnetworkprotocol.h"
#include <ntqeuckrcodec.h>
#include <ntqgb18030codec.h>
#include "ntqgcache.h"
#include <ntqgif.h>
#include <ntqglcolormap.h>
#include <ntqcache.h>
#include <ntqdropsite.h>
#include "ntqgplugin.h"
#include <ntqgrid.h>
#include "ntqrangecontrol.h"
#include "ntqbuttongroup.h"
#include <ntqdatetimeedit.h>
#include "ntqgvector.h"
#include "ntqhbox.h"
#include <ntqhbuttongroup.h>
#include <ntqhgroupbox.h>
#include "ntqsocketnotifier.h"
#include <ntqeventloop.h>
#include <ntqhttp.h>
#include <ntqaction.h>
#include "ntqbuffer.h"
#include "ntqimage.h"
#include <ntqimageformatplugin.h>
#include "ntqlineedit.h"
#include <ntqintcache.h>
#include "ntqintdict.h"
#include "ntqmotifstyle.h"
#include "ntqpicture.h"
#include <ntqjiscodec.h>
#include <ntqeucjpcodec.h>
#include <ntqkeycode.h>
#include <ntqaccel.h>
#include "ntqlabel.h"
#include "ntqlayout.h"
#include <ntqlcdnumber.h>
#include <ntqlibrary.h>
#include <ntqinputdialog.h>
#include "ntqscrollbar.h"
#include "ntqscrollview.h"
#include "ntqdir.h"
#include "ntqwindowsstyle.h"
#include "ntqconnection.h"
#include "ntqbitmap.h"
#include "ntqvariant.h"
#include "ntqsignal.h"
#include <ntqmessagebox.h>
#include "ntqmetaobject.h"
#include "ntqheader.h"
#include <ntqmotifplusstyle.h>
#include <ntqcdestyle.h>
#include <ntqmovie.h>
#include "ntqptrvector.h"
#include "ntqmutex.h"
#include <ntqnetwork.h>
#include <ntqftp.h>
#include "ntqguardedptr.h"
#include <ntqobjectcleanuphandler.h>
#include "ntqsqlfield.h"
#include <ntqobjectdict.h>
#include <ntqobjectlist.h>
#include <ntqcolordialog.h>
#include <ntqpaintdevicemetrics.h>
#include "ntqpointarray.h"
#include "ntqmenudata.h"
#include <ntqlistview.h>
#include "ntqpen.h"
#include "ntqdragobject.h"
#include <ntqiconview.h>
#include <ntqpixmapcache.h>
#include <ntqplatinumstyle.h>
#include <ntqpngio.h>
#include <ntqcursor.h>
#include <ntqerrormessage.h>
#include <ntqpolygonscanner.h>
#include "ntqpopupmenu.h"
#include <ntqprintdialog.h>
#include <ntqprinter.h>
#include <ntqprocess.h>
#include "ntqprogressbar.h"
#include "ntqsemimodal.h"
#include <ntqasciicache.h>
#include "ntqptrdict.h"
#include <ntqcleanuphandler.h>
#include <ntqptrqueue.h>
#include <ntqptrstack.h>
#include "ntqstylesheet.h"
#include <ntqpushbutton.h>
#include <ntqradiobutton.h>
#include <ntqdial.h>
#include <ntqdockarea.h>
#include "ntqregexp.h"
#include <ntqclipboard.h>
#include <ntqrtlcodec.h>
#include <ntqlistbox.h>
#include <ntqgridview.h>
#include "ntqsemaphore.h"
#include <ntqprogressdialog.h>
#include "ntqsocketdevice.h"
#include <ntqsessionmanager.h>
#include <ntqsettings.h>
#include <ntqsgistyle.h>
#include <ntqfontdialog.h>
#include "ntqtimer.h"
#include <ntqsignalmapper.h>
#include <ntqsignalslotimp.h>
#include <ntqsimplerichtext.h>
#include "ntqwmatrix.h"
#include <ntqsizegrip.h>
#include <ntqabstractlayout.h>
#include <ntqsjiscodec.h>
#include <ntqslider.h>
#include <ntqsocket.h>
#include <ntqserversocket.h>
#include <ntqdns.h>
#include <ntqsortedlist.h>
#include <ntqsound.h>
#include <ntqspinbox.h>
#include <ntqsplashscreen.h>
#include <ntqsplitter.h>
#include "ntqsqlerror.h"
#include "ntqeditorfactory.h"
#include "ntqsqlquery.h"
#include "ntqsqlrecord.h"
#include <ntqsqldriverplugin.h>
#include "ntqsqlindex.h"
#include "ntqsqlcursor.h"
#include <ntqsqldriver.h>
#include <ntqsqlform.h>
#include "ntqtable.h"
#include <ntqsqlpropertymap.h>
#include <ntqsqldatabase.h>
#include <ntqdatabrowser.h>
#include <ntqsqlresult.h>
#include <ntqsqlselectcursor.h>
#include <ntqstatusbar.h>
#include <ntqmenubar.h>
#include <ntqcanvas.h>
#include "ntqtranslator.h"
#include <ntqstrvec.h>
#include <ntqinterlacestyle.h>
#include <ntqstylefactory.h>
#include <ntqstyleplugin.h>
#include "ntqtextedit.h"
#include <ntqsyntaxhighlighter.h>
#include <ntqtabdialog.h>
#include "ntqsqleditorfactory.h"
#include <ntqtabwidget.h>
#include <ntqtextbrowser.h>
#include <ntqbig5codec.h>
#include <ntqtextcodecfactory.h>
#include <ntqtextcodecplugin.h>
#include <ntqmultilineedit.h>
#include "ntqtoolbar.h"
#include <ntqtextview.h>
#include "ntqwaitcondition.h"
#include <ntqasyncio.h>
#include <ntqfontdatabase.h>
#include <ntqmainwindow.h>
#include <ntqtoolbox.h>
#include <ntqtooltip.h>
#include "ntqdesktopwidget.h"
#include <ntqtsciicodec.h>
#include "ntqurl.h"
#include "ntqurloperator.h"
#include <ntqfiledialog.h>
#include <ntqutfcodec.h>
#include <ntquuid.h>
#include <ntqvalidator.h>
#include <ntqasyncimageio.h>
#include <ntqvaluestack.h>
#include <ntqvaluevector.h>
#include <ntqdatatable.h>
#include <ntqvbox.h>
#include <ntqvbuttongroup.h>
#include <ntqvfbhdr.h>
#include <ntqvgroupbox.h>
#include <ntqthread.h>
#include <ntqwhatsthis.h>
#include <ntqapplication.h>
#include <ntqwidgetintdict.h>
#include <ntqfocusdata.h>
#include <ntqwidgetplugin.h>
#include <ntqwidgetstack.h>
#include <ntqcheckbox.h>
#include <ntqcompactstyle.h>
#include <ntqwizard.h>
#include <ntqpainter.h>
#include <ntqworkspace.h>
#include <ntqlocalfs.h>
#include <ntqxml.h>

#if defined( QT_MOC_CPP ) || defined( QT_H_CPP ) || defined( Q_OS_MACX )
#include <private/qcom_p.h>
#include <private/qucom_p.h>
#include "private/qgfxdriverinterface_p.h"
#include "private/qcom_p.h"
#include "private/qimageformatinterface_p.h"
#include "private/qisciicodec_p.h"
#include "private/qkbddriverinterface_p.h"
#include "private/qlayoutengine_p.h"
#include "private/qcomlibrary_p.h"
#include "private/qmousedriverinterface_p.h"
#include "private/qeffects_p.h"
#include "private/qgpluginmanager_p.h"
#include "private/qinternal_p.h"
#include "private/qsqldriverinterface_p.h"
#include "private/qsqlmanager_p.h"
#include "private/qlock_p.h"
#include "private/qcomponentfactory_p.h"
#include "private/qstyleinterface_p.h"
#include "private/qrichtext_p.h"
#include "private/qsvgdevice_p.h"
#include "private/qfontcodecs_p.h"
#include "private/qtextcodecinterface_p.h"
#include "private/qpsprinter_p.h"
#include "private/qtitlebar_p.h"
#include "private/qucom_p.h"
#include "private/qucomextra_p.h"
#include "private/qpluginmanager_p.h"
#include "private/qdir_p.h"
#include "private/qsettings_p.h"
#include "private/qsqlextension_p.h"
#include "private/qdialogbuttons_p.h"
#include "private/qwidgetinterface_p.h"
#include "private/qwidgetresizehandler_p.h"
#include "private/qlibrary_p.h"
#endif // Private headers


#ifdef TQ_WS_X11
#include "private/tqttdeintegration_x11_p.h"
#endif

#ifdef TQ_WS_MAC
#include <qaquastyle.h>
#include <qmacstyle_mac.h>
#endif // TQ_WS_MAC

#ifdef TQ_WS_WIN
#include <qwindowsxpstyle.h>
#endif

#ifdef TQ_WS_QWS
#include <private/qtextengine_p.h>
#include "qfontmanager_qws.h"
#include <qfontfactorybdf_qws.h>
#include <qgfxvoodoodefs_qws.h>
#include <qgfxmatroxdefs_qws.h>
#include <qgfxdriverplugin_qws.h>
#include <qkbddriverfactory_qws.h>
#include <qkbddriverplugin_qws.h>
#include <qmousedriverfactory_qws.h>
#include <qmousedriverplugin_qws.h>
#include <qcopchannel_qws.h>
#include <qdirectpainter_qws.h>
#include "qmemorymanager_qws.h"
#include <qmouse_qws.h>
#include <qfontfactoryttf_qws.h>
#ifndef Q_OS_MAC
# include <qsoundqss_qws.h>
#endif
#include "qgfx_qws.h"
#include <qgfxdriverfactory_qws.h>
#include "qwsdisplay_qws.h"
#include "qwssocket_qws.h"
#include "qwsdecoration_qws.h"
#include "qwsutils_qws.h"
#include <qwscursor_qws.h>
#include "qwsmanager_qws.h"
#include "qwsdefaultdecoration_qws.h"
#include <qgfxraster_qws.h>
#include "qwscommand_qws.h"
#include <qwshydrodecoration_qws.h>
#include <qwskde2decoration_qws.h>
#include <qwskdedecoration_qws.h>
#include <qwsbeosdecoration_qws.h>
#include "qwsproperty_qws.h"
#include <qwsregionmanager_qws.h>
#include "qwsevent_qws.h"
#include <qwindowsystem_qws.h>
#include <qwswindowsdecoration_qws.h>
#endif // TQ_WS_QWS


#ifdef TQ_WS_WCE
#include <qpocketpcstyle_wce.h>
#endif // TQ_WS_WCE

#endif // QT_H
