/*
 * q1compat_map.h — Q→TQ 类名映射表（自动生成，勿手改）
 *
 * 【迁移脚手架·非最终架构】由 port/gen_q1compat.sh 从 tqt3/ 源码提取生成。
 * 用途：让尚未显式 TQ 化的 KDE1 模块在 TQt3 上编译通过；每模块显式化后
 * 即脱离此表，全部模块摘除完毕后本文件随 port/ 脚手架整体拆除。
 * tqt3 快照更新后须重跑生成。黑名单类（QList/QArray 等语义改名者）
 * 不在此表，见 q1compat.h 特判段。
 */
#ifndef Q1COMPAT_MAP_H
#define Q1COMPAT_MAP_H

#define QAccel TQAccel
#define QAccelManager TQAccelManager
#define QAccelPrivate TQAccelPrivate
#define QAccessible TQAccessible
#define QAccessibleFactoryInterface TQAccessibleFactoryInterface
#define QAccessibleInterface TQAccessibleInterface
#define QAccessibleObject TQAccessibleObject
#define QAction TQAction
#define QActionGroup TQActionGroup
#define QActionGroupPrivate TQActionGroupPrivate
#define QActionPrivate TQActionPrivate
#define QApplication TQApplication
#define QAsciiBucket TQAsciiBucket
#define QAsciiCache TQAsciiCache
#define QAsciiCacheIterator TQAsciiCacheIterator
#define QAsciiDict TQAsciiDict
#define QAsciiDictIterator TQAsciiDictIterator
#define QAsyncIO TQAsyncIO
#define QAuBucket TQAuBucket
#define QAuServer TQAuServer
#define QBackInsertIterator TQBackInsertIterator
#define QBaseApplication TQBaseApplication
#define QBaseBucket TQBaseBucket
#define QBig5Codec TQBig5Codec
#define QBig5hkscsCodec TQBig5hkscsCodec
#define QBitArray TQBitArray
#define QBitmap TQBitmap
#define QBitVal TQBitVal
#define QBoxLayout TQBoxLayout
#define QBoxLayoutData TQBoxLayoutData
#define QBrush TQBrush
#define QBrushData TQBrushData
#define QBuffer TQBuffer
#define QButton TQButton
#define QButtonData TQButtonData
#define QButtonGroup TQButtonGroup
#define QButtonList TQButtonList
#define QByteArray TQByteArray
#define QCacheIterator TQCacheIterator
#define QCanvas TQCanvas
#define QCanvasChunk TQCanvasChunk
#define QCanvasData TQCanvasData
#define QCanvasEllipse TQCanvasEllipse
#define QCanvasItem TQCanvasItem
#define QCanvasItemExtra TQCanvasItemExtra
#define QCanvasLine TQCanvasLine
#define QCanvasPixmap TQCanvasPixmap
#define QCanvasPixmapArray TQCanvasPixmapArray
#define QCanvasPolygon TQCanvasPolygon
#define QCanvasPolygonalItem TQCanvasPolygonalItem
#define QCanvasRectangle TQCanvasRectangle
#define QCanvasSprite TQCanvasSprite
#define QCanvasText TQCanvasText
#define QCanvasTextExtra TQCanvasTextExtra
#define QCanvasView TQCanvasView
#define QCanvasViewData TQCanvasViewData
#define QCDict TQCDict
#define QCEMainWindow TQCEMainWindow
#define QChar TQChar
#define QCharRef TQCharRef
#define QCheckBox TQCheckBox
#define QCheckListItem TQCheckListItem
#define QCheckListItemPrivate TQCheckListItemPrivate
#define QCheckTableItem TQCheckTableItem
#define QChildEvent TQChildEvent
#define QClassInfo TQClassInfo
#define QCleanupHandler TQCleanupHandler
#define QClipboard TQClipboard
#define QClipboardData TQClipboardData
#define QCList TQCList
#define QCListIt TQCListIt
#define QCloseEvent TQCloseEvent
#define QColor TQColor
#define QColorDialog TQColorDialog
#define QColorDialogPrivate TQColorDialogPrivate
#define QColorDrag TQColorDrag
#define QColorGroup TQColorGroup
#define QColorGroupPrivate TQColorGroupPrivate
#define QColorShower TQColorShower
#define QComboBox TQComboBox
#define QComboBoxData TQComboBoxData
#define QComboBoxPopupItem TQComboBoxPopupItem
#define QComboTableItem TQComboTableItem
#define QCommonStyle TQCommonStyle
#define QConnection TQConnection
#define QConnectionList TQConnectionList
#define QConnectionListIt TQConnectionListIt
#define QConstString TQConstString
#define QContextMenuEvent TQContextMenuEvent
#define QCoreApplicationThread TQCoreApplicationThread
#define QCString TQCString
#define QCursor TQCursor
#define QCursorData TQCursorData
#define QCustomEvent TQCustomEvent
#define QCustomMenuItem TQCustomMenuItem
#define QDataBrowser TQDataBrowser
#define QDataBrowserPrivate TQDataBrowserPrivate
#define QDataPump TQDataPump
#define QDataSink TQDataSink
#define QDataSource TQDataSource
#define QDataStream TQDataStream
#define QDataTablePrivate TQDataTablePrivate
#define QDataViewPrivate TQDataViewPrivate
#define QDate TQDate
#define QDateEdit TQDateEdit
#define QDateEditPrivate TQDateEditPrivate
#define QDateTime TQDateTime
#define QDateTimeEdit TQDateTimeEdit
#define QDateTimeEditBase TQDateTimeEditBase
#define QDateTimeEditPrivate TQDateTimeEditPrivate
#define QDeepCopy TQDeepCopy
#define QDesktopWidget TQDesktopWidget
#define QDesktopWidgetPrivate TQDesktopWidgetPrivate
#define QDial TQDial
#define QDialog TQDialog
#define QDialogPrivate TQDialogPrivate
#define QDialPrivate TQDialPrivate
#define QDict TQDict
#define QDictIterator TQDictIterator
#define QDir TQDir
#define QDirSortItem TQDirSortItem
#define QDiskFont TQDiskFont
#define QDnsAnswer TQDnsAnswer
#define QDnsManager TQDnsManager
#define QDnsPrivate TQDnsPrivate
#define QDnsSocket TQDnsSocket
#define QDockArea TQDockArea
#define QDockAreaLayout TQDockAreaLayout
#define QDockAreaPrivate TQDockAreaPrivate
#define QDockWindow TQDockWindow
#define QDockWindowHandle TQDockWindowHandle
#define QDockWindowPrivate TQDockWindowPrivate
#define QDockWindowResizeHandle TQDockWindowResizeHandle
#define QDockWindowTitleBar TQDockWindowTitleBar
#define QDomAttr TQDomAttr
#define QDomAttrPrivate TQDomAttrPrivate
#define QDomCDATASection TQDomCDATASection
#define QDomCDATASectionPrivate TQDomCDATASectionPrivate
#define QDomCharacterData TQDomCharacterData
#define QDomCharacterDataPrivate TQDomCharacterDataPrivate
#define QDomComment TQDomComment
#define QDomCommentPrivate TQDomCommentPrivate
#define QDomDocument TQDomDocument
#define QDomDocumentFragment TQDomDocumentFragment
#define QDomDocumentFragmentPrivate TQDomDocumentFragmentPrivate
#define QDomDocumentPrivate TQDomDocumentPrivate
#define QDomDocumentType TQDomDocumentType
#define QDomDocumentTypePrivate TQDomDocumentTypePrivate
#define QDomElement TQDomElement
#define QDomElementPrivate TQDomElementPrivate
#define QDomEntity TQDomEntity
#define QDomEntityPrivate TQDomEntityPrivate
#define QDomEntityReference TQDomEntityReference
#define QDomEntityReferencePrivate TQDomEntityReferencePrivate
#define QDomImplementation TQDomImplementation
#define QDomImplementationPrivate TQDomImplementationPrivate
#define QDomNamedNodeMap TQDomNamedNodeMap
#define QDomNamedNodeMapPrivate TQDomNamedNodeMapPrivate
#define QDomNode TQDomNode
#define QDomNodeList TQDomNodeList
#define QDomNodeListPrivate TQDomNodeListPrivate
#define QDomNodePrivate TQDomNodePrivate
#define QDomNotation TQDomNotation
#define QDomNotationPrivate TQDomNotationPrivate
#define QDomProcessingInstruction TQDomProcessingInstruction
#define QDomProcessingInstructionPrivate TQDomProcessingInstructionPrivate
#define QDomText TQDomText
#define QDomTextPrivate TQDomTextPrivate
#define QDoubleValidator TQDoubleValidator
#define QDragEnterEvent TQDragEnterEvent
#define QDragLeaveEvent TQDragLeaveEvent
#define QDragManager TQDragManager
#define QDragMoveEvent TQDragMoveEvent
#define QDragObject TQDragObject
#define QDragObjectData TQDragObjectData
#define QDragResponseEvent TQDragResponseEvent
#define QDropEvent TQDropEvent
#define QDropSite TQDropSite
#define QErrorMessage TQErrorMessage
#define QETWidget TQETWidget
#define QEvent TQEvent
#define QEventLoop TQEventLoop
#define QEventLoopPrivate TQEventLoopPrivate
#define QEventLoopThread TQEventLoopThread
#define Q_EXPORT_CODECS_CN TQ_EXPORT_CODECS_CN
#define Q_EXPORT_CODECS_JP TQ_EXPORT_CODECS_JP
#define Q_EXPORT_CODECS_KR TQ_EXPORT_CODECS_KR
#define Q_EXPORT_STYLE_CDE TQ_EXPORT_STYLE_CDE
#define Q_EXPORT_STYLE_COMPACT TQ_EXPORT_STYLE_COMPACT
#define Q_EXPORT_STYLE_MOTIF TQ_EXPORT_STYLE_MOTIF
#define Q_EXPORT_STYLE_MOTIFPLUS TQ_EXPORT_STYLE_MOTIFPLUS
#define Q_EXPORT_STYLE_PLATINUM TQ_EXPORT_STYLE_PLATINUM
#define Q_EXPORT_STYLE_SGI TQ_EXPORT_STYLE_SGI
#define Q_EXPORT_STYLE_WINDOWS TQ_EXPORT_STYLE_WINDOWS
#define QFile TQFile
#define QFileDialog TQFileDialog
#define QFileDialogPrivate TQFileDialogPrivate
#define QFileDialogTQFileListView TQFileDialogTQFileListView
#define QFileIconProvider TQFileIconProvider
#define QFileInfo TQFileInfo
#define QFileInfoCache TQFileInfoCache
#define QFileListBox TQFileListBox
#define QFilePreview TQFilePreview
#define QFilePrivate TQFilePrivate
#define QFocusData TQFocusData
#define QFocusEvent TQFocusEvent
#define QFontDatabase TQFontDatabase
#define QFontDatabasePrivate TQFontDatabasePrivate
#define QFontDef TQFontDef
#define QFontDialog TQFontDialog
#define QFontDialogPrivate TQFontDialogPrivate
#define QFontEngine TQFontEngine
#define QFontEngineBox TQFontEngineBox
#define QFontEngineLatinXLFD TQFontEngineLatinXLFD
#define QFontEngineMac TQFontEngineMac
#define QFontEngineWin TQFontEngineWin
#define QFontEngineXft TQFontEngineXft
#define QFontEngineXLFD TQFontEngineXLFD
#define QFontMetrics TQFontMetrics
#define QFontPrivate TQFontPrivate
#define QFontStylePrivate TQFontStylePrivate
#define QFrame TQFrame
#define QFtpCommand TQFtpCommand
#define QGArray TQGArray
#define QGCacheIterator TQGCacheIterator
#define QGDictIterator TQGDictIterator
#define QGDItList TQGDItList
#define QGfx TQGfx
#define QGLayoutIterator TQGLayoutIterator
#define QGLCmap TQGLCmap
#define QGLContext TQGLContext
#define QGListIterator TQGListIterator
#define QGListIteratorList TQGListIteratorList
#define QGListPrivate TQGListPrivate
#define QGListStdIterator TQGListStdIterator
#define QGLOverlayWidget TQGLOverlayWidget
#define QGLWidget TQGLWidget
#define QGPlugin TQGPlugin
#define QGrid TQGrid
#define QGridLayout TQGridLayout
#define QGridLayoutBox TQGridLayoutBox
#define QGridLayoutData TQGridLayoutData
#define QGridView TQGridView
#define QGridViewPrivate TQGridViewPrivate
#define QGroupBox TQGroupBox
#define QGroupBoxPrivate TQGroupBoxPrivate
#define QGuardedPtr TQGuardedPtr
#define QGuardedPtrPrivate TQGuardedPtrPrivate
#define QHBox TQHBox
#define QHBoxLayout TQHBoxLayout
#define QHButtonGroup TQHButtonGroup
#define QHeader TQHeader
#define QHeaderData TQHeaderData
#define QHebrewCodec TQHebrewCodec
#define QHGroupBox TQHGroupBox
#define QHideDock TQHideDock
#define QHideEvent TQHideEvent
#define QHostAddressPrivate TQHostAddressPrivate
#define QHttp TQHttp
#define QHttpCloseRequest TQHttpCloseRequest
#define QHttpNormalRequest TQHttpNormalRequest
#define QHttpPGHRequest TQHttpPGHRequest
#define QHttpPrivate TQHttpPrivate
#define QHttpRequest TQHttpRequest
#define QHttpSetHostRequest TQHttpSetHostRequest
#define QIconDrag TQIconDrag
#define QIconDragEvent TQIconDragEvent
#define QIconDragItem TQIconDragItem
#define QIconDragPrivate TQIconDragPrivate
#define QIconFactory TQIconFactory
#define QIconSet TQIconSet
#define QIconSetPrivate TQIconSetPrivate
#define QIconView TQIconView
#define QIconViewItem TQIconViewItem
#define QIconViewItemLineEdit TQIconViewItemLineEdit
#define QIconViewItemPrivate TQIconViewItemPrivate
#define QIconViewPrivate TQIconViewPrivate
#define QIconViewToolTip TQIconViewToolTip
#define QImage TQImage
#define QImageConsumer TQImageConsumer
#define QImageData TQImageData
#define QImageDataMisc TQImageDataMisc
#define QImageDecoder TQImageDecoder
#define QImageDecoderPrivate TQImageDecoderPrivate
#define QImageDrag TQImageDrag
#define QImageDragData TQImageDragData
#define QImageFormat TQImageFormat
#define QImageFormatPlugin TQImageFormatPlugin
#define QImageFormatPluginPrivate TQImageFormatPluginPrivate
#define QImageFormatType TQImageFormatType
#define QImageIO TQImageIO
#define QImageIOData TQImageIOData
#define QImageTextKeyLang TQImageTextKeyLang
#define QIMComposeEvent TQIMComposeEvent
#define QIMEvent TQIMEvent
#define QInputContext TQInputContext
#define QInputContextFactory TQInputContextFactory
#define QInputContextMenu TQInputContextMenu
#define QInputContextPlugin TQInputContextPlugin
#define QInputContextPluginPrivate TQInputContextPluginPrivate
#define QInputContextPrivate TQInputContextPrivate
#define QInputDialog TQInputDialog
#define QInputDialogPrivate TQInputDialogPrivate
#define QIntBucket TQIntBucket
#define QIntCache TQIntCache
#define QIntCacheIterator TQIntCacheIterator
#define QIntDict TQIntDict
#define QIntDictIterator TQIntDictIterator
#define QInterlaceStyle TQInterlaceStyle
#define QInternal TQInternal
#define QIntValidator TQIntValidator
#define QIODevice TQIODevice
#define QIODeviceSource TQIODeviceSource
#define QKeyEvent TQKeyEvent
#define QKeySequence TQKeySequence
#define QKeySequencePrivate TQKeySequencePrivate
#define QLabel TQLabel
#define QLabelPrivate TQLabelPrivate
#define QLayout TQLayout
#define QLayoutData TQLayoutData
#define QLayoutItem TQLayoutItem
#define QLayoutIterator TQLayoutIterator
#define QLCDNumber TQLCDNumber
#define QLCDNumberPrivate TQLCDNumberPrivate
#define QLibrary TQLibrary
#define QLibraryPrivate TQLibraryPrivate
#define QLineEdit TQLineEdit
#define QLineEditPrivate TQLineEditPrivate
#define QListBox TQListBox
#define QListBoxItem TQListBoxItem
#define QListBoxPixmap TQListBoxPixmap
#define QListBoxPrivate TQListBoxPrivate
#define QListBoxText TQListBoxText
#define QListView TQListView
#define QListViewItem TQListViewItem
#define QListViewItemIterator TQListViewItemIterator
#define QListViewItemIteratorPrivate TQListViewItemIteratorPrivate
#define QListViewPrivate TQListViewPrivate
#define QListViewToolTip TQListViewToolTip
#define QLNode TQLNode
#define QLocale TQLocale
#define QLocalePrivate TQLocalePrivate
#define QLocalFs TQLocalFs
#define QMacDndExtra TQMacDndExtra
#define QMacInputMethod TQMacInputMethod
#define QMacMime TQMacMime
#define QMacPainter TQMacPainter
#define QMacSavedPortInfo TQMacSavedPortInfo
#define QMainWindow TQMainWindow
#define QMainWindowLayout TQMainWindowLayout
#define QMainWindowPrivate TQMainWindowPrivate
#define QMap TQMap
#define QMapConstIterator TQMapConstIterator
#define QMapIterator TQMapIterator
#define QMapNode TQMapNode
#define QMapNodeBase TQMapNodeBase
#define QMapPrivate TQMapPrivate
#define QMapPrivateBase TQMapPrivateBase
#define QMCPI TQMCPI
#define QMemArray TQMemArray
#define QMemberDict TQMemberDict
#define QMembuf TQMembuf
#define QMenuBar TQMenuBar
#define QMenuData TQMenuData
#define QMenuDataData TQMenuDataData
#define QMenuItem TQMenuItem
#define QMenuItemData TQMenuItemData
#define QMessageBox TQMessageBox
#define QMessageBoxData TQMessageBoxData
#define QMetaData TQMetaData
#define QMetaEnum TQMetaEnum
#define QMetaObject TQMetaObject
#define QMetaObjectCleanUp TQMetaObjectCleanUp
#define QMetaObjectPrivate TQMetaObjectPrivate
#define QMetaProperty TQMetaProperty
#define QM_EXPORT_CANVAS TQM_EXPORT_CANVAS
#define QM_EXPORT_DNS TQM_EXPORT_DNS
#define QM_EXPORT_DOM TQM_EXPORT_DOM
#define QM_EXPORT_FTP TQM_EXPORT_FTP
#define QM_EXPORT_HTTP TQM_EXPORT_HTTP
#define QM_EXPORT_NETWORK TQM_EXPORT_NETWORK
#define QM_EXPORT_OPENGL TQM_EXPORT_OPENGL
#define QM_EXPORT_SQL TQM_EXPORT_SQL
#define QM_EXPORT_TABLE TQM_EXPORT_TABLE
#define QM_EXPORT_WORKSPACE TQM_EXPORT_WORKSPACE
#define QM_EXPORT_XML TQM_EXPORT_XML
#define QMimeSource TQMimeSource
#define QMimeSourceFactory TQMimeSourceFactory
#define QMimeSourceFactoryData TQMimeSourceFactoryData
#define QMouseEvent TQMouseEvent
#define QMoveEvent TQMoveEvent
#define QMovie TQMovie
#define QMoviePrivate TQMoviePrivate
#define QMultiCellPixmap TQMultiCellPixmap
#define QMultiLineEdit TQMultiLineEdit
#define QMultiLineEditCommand TQMultiLineEditCommand
#define QMultiLineEditData TQMultiLineEditData
#define QMutex TQMutex
#define QMutexLocker TQMutexLocker
#define QMutexPrivate TQMutexPrivate
#define QNetworkOperation TQNetworkOperation
#define QNetworkOperationPrivate TQNetworkOperationPrivate
#define QNetworkProtocol TQNetworkProtocol
#define QNetworkProtocolFactory TQNetworkProtocolFactory
#define QNetworkProtocolFactoryBase TQNetworkProtocolFactoryBase
#define QNetworkProtocolPrivate TQNetworkProtocolPrivate
#define QObject TQObject
#define QObjectCleanupHandler TQObjectCleanupHandler
#define QObjectDictionary TQObjectDictionary
#define QObjectList TQObjectList
#define QObjectListIt TQObjectListIt
#define QObjectListIterator TQObjectListIterator
#define QObjectPrivate TQObjectPrivate
#define QObjectUserData TQObjectUserData
#define QOleDropTarget TQOleDropTarget
#define QPaintDevice TQPaintDevice
#define QPaintDeviceMetrics TQPaintDeviceMetrics
#define QPaintDeviceX11Data TQPaintDeviceX11Data
#define QPainter TQPainter
#define QPainterPrivate TQPainterPrivate
#define QPaintEvent TQPaintEvent
#define QPair TQPair
#define QPalData TQPalData
#define QPalette TQPalette
#define QPen TQPen
#define QPenData TQPenData
#define QPicture TQPicture
#define QPicturePrivate TQPicturePrivate
#define QPixmap TQPixmap
#define QPixmapCache TQPixmapCache
#define QPixmapData TQPixmapData
#define QPixmapPrivate TQPixmapPrivate
#define QPoint TQPoint
#define QPointArray TQPointArray
#define QPolygonalProcessor TQPolygonalProcessor
#define QPolygonScanner TQPolygonScanner
#define QPopupMenu TQPopupMenu
#define QPopupMenuPrivate TQPopupMenuPrivate
#define QPostEventList TQPostEventList
#define QPrintDialog TQPrintDialog
#define QPrintDialogPrivate TQPrintDialogPrivate
#define QPrinter TQPrinter
#define QPrinterPrivate TQPrinterPrivate
#define QProc TQProc
#define QProcess TQProcess
#define QProcessManager TQProcessManager
#define QProcessPrivate TQProcessPrivate
#define QProgressBar TQProgressBar
#define QProgressBarPrivate TQProgressBarPrivate
#define QProgressDialog TQProgressDialog
#define QProgressDialogData TQProgressDialogData
#define QPSPrinterFont TQPSPrinterFont
#define QPtrBucket TQPtrBucket
#define QPtrCollection TQPtrCollection
#define QPtrDict TQPtrDict
#define QPtrDictIterator TQPtrDictIterator
#define QPtrList TQPtrList
#define QPtrListIterator TQPtrListIterator
#define QPtrListStdIterator TQPtrListStdIterator
#define QPtrQueue TQPtrQueue
#define QPtrStack TQPtrStack
#define QPtrVector TQPtrVector
#define QPushButton TQPushButton
#define QPushButtonPrivate TQPushButtonPrivate
#define QRadioButton TQRadioButton
#define QRangeControl TQRangeControl
#define QRangeControlPrivate TQRangeControlPrivate
#define QRect TQRect
#define QRegExp TQRegExp
#define QRegExpEngine TQRegExpEngine
#define QRegExpPrivate TQRegExpPrivate
#define QRegExpValidator TQRegExpValidator
#define QRegion TQRegion
#define QRegionData TQRegionData
#define QRegionPrivate TQRegionPrivate
#define QResizeEvent TQResizeEvent
#define QScreen TQScreen
#define QScrollBar TQScrollBar
#define QScrollView TQScrollView
#define QScrollViewData TQScrollViewData
#define QSemaphore TQSemaphore
#define QSemaphorePrivate TQSemaphorePrivate
#define QSemiModal TQSemiModal
#define QSenderObjectList TQSenderObjectList
#define QServerSocketPrivate TQServerSocketPrivate
#define QSessionManager TQSessionManager
#define QSessionManagerData TQSessionManagerData
#define QSettings TQSettings
#define QSettingsPrivate TQSettingsPrivate
#define QSGIStylePrivate TQSGIStylePrivate
#define QShared TQShared
#define QSharedCleanupHandler TQSharedCleanupHandler
#define QShowEvent TQShowEvent
#define QSignal TQSignal
#define QSignalMapper TQSignalMapper
#define QSignalMapperData TQSignalMapperData
#define QSignalMapperRec TQSignalMapperRec
#define QSignalVec TQSignalVec
#define QSimpleRichText TQSimpleRichText
#define QSimpleRichTextData TQSimpleRichTextData
#define QSingleCleanupHandler TQSingleCleanupHandler
#define QSize TQSize
#define QSizeGrip TQSizeGrip
#define QSizePolicy TQSizePolicy
#define QSlider TQSlider
#define QSliderPrivate TQSliderPrivate
#define QSocket TQSocket
#define QSocketDevice TQSocketDevice
#define QSocketDevicePrivate TQSocketDevicePrivate
#define QSocketNotifier TQSocketNotifier
#define QSocketPrivate TQSocketPrivate
#define QSortedList TQSortedList
#define QSound TQSound
#define QSoundData TQSoundData
#define QSpacerItem TQSpacerItem
#define QSpinBox TQSpinBox
#define QSpinBoxPrivate TQSpinBoxPrivate
#define QSpinWidget TQSpinWidget
#define QSpinWidgetPrivate TQSpinWidgetPrivate
#define QSplashScreen TQSplashScreen
#define QSplashScreenPrivate TQSplashScreenPrivate
#define QSplitter TQSplitter
#define QSplitterHandle TQSplitterHandle
#define QSplitterLayoutStruct TQSplitterLayoutStruct
#define QSplitterPrivate TQSplitterPrivate
#define QSql TQSql
#define QSqlCursor TQSqlCursor
#define QSqlCursorPrivate TQSqlCursorPrivate
#define QSqlDatabase TQSqlDatabase
#define QSqlDatabasePrivate TQSqlDatabasePrivate
#define QSqlDriver TQSqlDriver
#define QSqlDriverExtension TQSqlDriverExtension
#define QSqlDriverPlugin TQSqlDriverPlugin
#define QSqlDriverPluginPrivate TQSqlDriverPluginPrivate
#define QSqlEditorFactory TQSqlEditorFactory
#define QSqlError TQSqlError
#define QSqlExtension TQSqlExtension
#define QSqlField TQSqlField
#define QSqlFieldInfoPrivate TQSqlFieldInfoPrivate
#define QSqlFieldPrivate TQSqlFieldPrivate
#define QSqlForm TQSqlForm
#define QSqlFormPrivate TQSqlFormPrivate
#define QSqlIndex TQSqlIndex
#define QSqlPropertyMap TQSqlPropertyMap
#define QSqlPropertyMapPrivate TQSqlPropertyMapPrivate
#define QSqlQuery TQSqlQuery
#define QSqlRecord TQSqlRecord
#define QSqlRecordInfo TQSqlRecordInfo
#define QSqlRecordPrivate TQSqlRecordPrivate
#define QSqlRecordShared TQSqlRecordShared
#define QSqlResult TQSqlResult
#define QSqlResultPrivate TQSqlResultPrivate
#define QSqlResultShared TQSqlResultShared
#define QSqlSelectCursorPrivate TQSqlSelectCursorPrivate
#define QStatusBar TQStatusBar
#define QStatusBarPrivate TQStatusBarPrivate
#define QStoredDrag TQStoredDrag
#define QStoredDragData TQStoredDragData
#define QStrIList TQStrIList
#define QString TQString
#define QStringBucket TQStringBucket
#define QStringData TQStringData
#define QStringList TQStringList
#define QStrIVec TQStrIVec
#define QStrList TQStrList
#define QStrListIterator TQStrListIterator
#define QStrVec TQStrVec
#define QStyle TQStyle
#define QStyleControlElementCheckListItemData TQStyleControlElementCheckListItemData
#define QStyleControlElementData TQStyleControlElementData
#define QStyleControlElementDataPrivate TQStyleControlElementDataPrivate
#define QStyleControlElementDockWidgetData TQStyleControlElementDockWidgetData
#define QStyleControlElementGenericWidgetData TQStyleControlElementGenericWidgetData
#define QStyleControlElementListViewData TQStyleControlElementListViewData
#define QStyleControlElementPopupMenuData TQStyleControlElementPopupMenuData
#define QStyleControlElementSpinWidgetData TQStyleControlElementSpinWidgetData
#define QStyleControlElementTabBarData TQStyleControlElementTabBarData
#define QStyleControlElementTitleBarData TQStyleControlElementTitleBarData
#define QStyleControlElementToolBarWidgetData TQStyleControlElementToolBarWidgetData
#define QStyleFactory TQStyleFactory
#define QStyleHintReturn TQStyleHintReturn
#define QStyleOption TQStyleOption
#define QStylePlugin TQStylePlugin
#define QStylePluginPrivate TQStylePluginPrivate
#define QStylePrivate TQStylePrivate
#define QStyleSheet TQStyleSheet
#define QStyleSheetItem TQStyleSheetItem
#define QStyleSheetItemData TQStyleSheetItemData
#define QStyleWidgetActionRequestData TQStyleWidgetActionRequestData
#define QSyntaxHighlighter TQSyntaxHighlighter
#define QSyntaxHighlighterInternal TQSyntaxHighlighterInternal
#define QSyntaxHighlighterPrivate TQSyntaxHighlighterPrivate
#define Qt TQt
#define QTab TQTab
#define QTabBar TQTabBar
#define QTabBarToolTip TQTabBarToolTip
#define QTabDialog TQTabDialog
#define QTabDialogPrivate TQTabDialogPrivate
#define QTable TQTable
#define QTableHeader TQTableHeader
#define QTableHeaderPrivate TQTableHeaderPrivate
#define QTableItem TQTableItem
#define QTablePrivate TQTablePrivate
#define QTabletEvent TQTabletEvent
#define QTabPrivate TQTabPrivate
#define QTabWidget TQTabWidget
#define QTabWidgetData TQTabWidgetData
#define QTextBrowser TQTextBrowser
#define QTextBrowserData TQTextBrowserData
#define QTextCodec TQTextCodec
#define QTextCodecFactory TQTextCodecFactory
#define QTextCodecPlugin TQTextCodecPlugin
#define QTextCodecPluginPrivate TQTextCodecPluginPrivate
#define QTextCommand TQTextCommand
#define QTextCursor TQTextCursor
#define QTextCustomItem TQTextCustomItem
#define QTextDecoder TQTextDecoder
#define QTextDocument TQTextDocument
#define QTextDrag TQTextDrag
#define QTextDragPrivate TQTextDragPrivate
#define QTextEdit TQTextEdit
#define QTextEditOptimPrivate TQTextEditOptimPrivate
#define QTextEditPrivate TQTextEditPrivate
#define QTextEncoder TQTextEncoder
#define QTextFormat TQTextFormat
#define QTextFormatCollection TQTextFormatCollection
#define QTextIStream TQTextIStream
#define QTextItem TQTextItem
#define QTextLayout TQTextLayout
#define QTextOStream TQTextOStream
#define QTextOStreamIterator TQTextOStreamIterator
#define QTextParag TQTextParag
#define QTextParagraph TQTextParagraph
#define QTextStream TQTextStream
#define QTextStreamPrivate TQTextStreamPrivate
#define QTextString TQTextString
#define QTextView TQTextView
#define QtFontFamily TQtFontFamily
#define QtFontFoundry TQtFontFoundry
#define QtFontStyle TQtFontStyle
#define QThread TQThread
#define QThreadInstance TQThreadInstance
#define QThreadStorage TQThreadStorage
#define QThreadStorageData TQThreadStorageData
#define QTime TQTime
#define QTimeEdit TQTimeEdit
#define QTimeEditPrivate TQTimeEditPrivate
#define QTimer TQTimer
#define QTimerEvent TQTimerEvent
#define QTipLabel TQTipLabel
#define QTipManager TQTipManager
#define QTLWExtra TQTLWExtra
#define QToolBar TQToolBar
#define QToolBarPrivate TQToolBarPrivate
#define QToolBox TQToolBox
#define QToolBoxPrivate TQToolBoxPrivate
#define QToolButton TQToolButton
#define QToolButtonPrivate TQToolButtonPrivate
#define QToolTip TQToolTip
#define QToolTipGroup TQToolTipGroup
#define QTranslator TQTranslator
#define QTranslatorMessage TQTranslatorMessage
#define QTranslatorPrivate TQTranslatorPrivate
#define QTsciiCodec TQTsciiCodec
#define QTSManip TQTSManip
#define QUMethod TQUMethod
#define QUndoRedoInfoPrivate TQUndoRedoInfoPrivate
#define QUnknownInterface TQUnknownInterface
#define QUObject TQUObject
#define QUriDrag TQUriDrag
#define QUrl TQUrl
#define QUrlInfo TQUrlInfo
#define QUrlInfoPrivate TQUrlInfoPrivate
#define QUrlOperator TQUrlOperator
#define QUrlOperatorPrivate TQUrlOperatorPrivate
#define QUrlPrivate TQUrlPrivate
#define QUtf16Codec TQUtf16Codec
#define QUtf8Codec TQUtf8Codec
#define QUuid TQUuid
#define QValidator TQValidator
#define QValueList TQValueList
#define QValueListConstIterator TQValueListConstIterator
#define QValueListIterator TQValueListIterator
#define QValueListNode TQValueListNode
#define QValueListPrivate TQValueListPrivate
#define QValueStack TQValueStack
#define QValueVector TQValueVector
#define QValueVectorPrivate TQValueVectorPrivate
#define QVariant TQVariant
#define QVBox TQVBox
#define QVBoxLayout TQVBoxLayout
#define QVButtonGroup TQVButtonGroup
#define QVFbHeader TQVFbHeader
#define QVFbKeyData TQVFbKeyData
#define QVGroupBox TQVGroupBox
#define QWaitCondition TQWaitCondition
#define QWaitConditionPrivate TQWaitConditionPrivate
#define QWExtra TQWExtra
#define QWhatsThis TQWhatsThis
#define QWheelEvent TQWheelEvent
#define QWidget TQWidget
#define QWidgetContainerPlugin TQWidgetContainerPlugin
#define QWidgetContainerPluginPrivate TQWidgetContainerPluginPrivate
#define QWidgetIntDict TQWidgetIntDict
#define QWidgetIntDictIt TQWidgetIntDictIt
#define QWidgetItem TQWidgetItem
#define QWidgetList TQWidgetList
#define QWidgetListIt TQWidgetListIt
#define QWidgetMapper TQWidgetMapper
#define QWidgetPlugin TQWidgetPlugin
#define QWidgetPluginPrivate TQWidgetPluginPrivate
#define QWidgetResizeHandler TQWidgetResizeHandler
#define QWidgetStack TQWidgetStack
#define QWidgetStackPrivate TQWidgetStackPrivate
#define QWindowsMime TQWindowsMime
#define QWindowsXPStyle TQWindowsXPStyle
#define QWizard TQWizard
#define QWizardPrivate TQWizardPrivate
#define QWMatrix TQWMatrix
#define QWorkspaceChild TQWorkspaceChild
#define QWorkspacePrivate TQWorkspacePrivate
#define QWSDecoration TQWSDecoration
#define QWSDisplay TQWSDisplay
#define QWSEvent TQWSEvent
#define QWSManager TQWSManager
#define QWSRegionManager TQWSRegionManager
#define QXmlAttributes TQXmlAttributes
#define QXmlAttributesPrivate TQXmlAttributesPrivate
#define QXmlContentHandler TQXmlContentHandler
#define QXmlDeclHandler TQXmlDeclHandler
#define QXmlDefaultHandler TQXmlDefaultHandler
#define QXmlDefaultHandlerPrivate TQXmlDefaultHandlerPrivate
#define QXmlDTDHandler TQXmlDTDHandler
#define QXmlEntityResolver TQXmlEntityResolver
#define QXmlErrorHandler TQXmlErrorHandler
#define QXmlInputSource TQXmlInputSource
#define QXmlInputSourcePrivate TQXmlInputSourcePrivate
#define QXmlLexicalHandler TQXmlLexicalHandler
#define QXmlLocator TQXmlLocator
#define QXmlLocatorPrivate TQXmlLocatorPrivate
#define QXmlNamespaceSupport TQXmlNamespaceSupport
#define QXmlNamespaceSupportPrivate TQXmlNamespaceSupportPrivate
#define QXmlParseException TQXmlParseException
#define QXmlParseExceptionPrivate TQXmlParseExceptionPrivate
#define QXmlReader TQXmlReader
#define QXmlSimpleReader TQXmlSimpleReader
#define QXmlSimpleReaderLocator TQXmlSimpleReaderLocator
#define QXmlSimpleReaderPrivate TQXmlSimpleReaderPrivate

/* Qt1→Qt3 语义改名映射（Qt1 名 → TQt3 实际类） */
#define QList TQPtrList
#define QListIterator TQPtrListIterator
#define QArray TQMemArray
#define QArrayIterator TQMemArrayIterator
#define QCollection TQPtrCollection
#define QStack TQPtrStack
#define QQueue TQPtrQueue

#endif // Q1COMPAT_MAP_H
