/*
 * qkeycode.h — Qt1 键码宏 → TQt3 枚举映射（迁移脚手架，自动生成）
 * Qt1: #define Key_Escape 0x1000（全局宏）；TQt3: TQt::Key_Escape 枚举。
 * 键名与键值 Qt1→Qt3 一脉相承，机械映射；模块显式化后随 port/ 拆除。
 */
#ifndef Q1FW_QKEYCODE_H
#define Q1FW_QKEYCODE_H
#include <ntqnamespace.h>
#define Key_0 TQt::Key_0
#define Key_1 TQt::Key_1
#define Key_2 TQt::Key_2
#define Key_3 TQt::Key_3
#define Key_4 TQt::Key_4
#define Key_5 TQt::Key_5
#define Key_6 TQt::Key_6
#define Key_7 TQt::Key_7
#define Key_8 TQt::Key_8
#define Key_9 TQt::Key_9
#define Key_A TQt::Key_A
#define Key_aacute TQt::Key_aacute
#define Key_Aacute TQt::Key_Aacute
#define Key_acircumflex TQt::Key_acircumflex
#define Key_Acircumflex TQt::Key_Acircumflex
#define Key_acute TQt::Key_acute
#define Key_adiaeresis TQt::Key_adiaeresis
#define Key_Adiaeresis TQt::Key_Adiaeresis
#define Key_ae TQt::Key_ae
#define Key_AE TQt::Key_AE
#define Key_agrave TQt::Key_agrave
#define Key_Agrave TQt::Key_Agrave
#define Key_Alt TQt::Key_Alt
#define Key_Ampersand TQt::Key_Ampersand
#define Key_Apostrophe TQt::Key_Apostrophe
#define Key_aring TQt::Key_aring
#define Key_Aring TQt::Key_Aring
#define Key_AsciiCircum TQt::Key_AsciiCircum
#define Key_AsciiTilde TQt::Key_AsciiTilde
#define Key_Asterisk TQt::Key_Asterisk
#define Key_At TQt::Key_At
#define Key_atilde TQt::Key_atilde
#define Key_Atilde TQt::Key_Atilde
#define Key_B TQt::Key_B
#define Key_Backslash TQt::Key_Backslash
#define Key_Backspace TQt::Key_Backspace
#define Key_Backtab TQt::Key_Backtab
#define Key_Bar TQt::Key_Bar
#define Key_BraceLeft TQt::Key_BraceLeft
#define Key_BraceRight TQt::Key_BraceRight
#define Key_BracketLeft TQt::Key_BracketLeft
#define Key_BracketRight TQt::Key_BracketRight
#define Key_brokenbar TQt::Key_brokenbar
#define Key_C TQt::Key_C
#define Key_CapsLock TQt::Key_CapsLock
#define Key_ccedilla TQt::Key_ccedilla
#define Key_Ccedilla TQt::Key_Ccedilla
#define Key_cedilla TQt::Key_cedilla
#define Key_cent TQt::Key_cent
#define Key_Colon TQt::Key_Colon
#define Key_Comma TQt::Key_Comma
#define Key_Control TQt::Key_Control
#define Key_copyright TQt::Key_copyright
#define Key_currency TQt::Key_currency
#define Key_D TQt::Key_D
#define Key_degree TQt::Key_degree
#define Key_Delete TQt::Key_Delete
#define Key_diaeresis TQt::Key_diaeresis
#define Key_division TQt::Key_division
#define Key_Dollar TQt::Key_Dollar
#define Key_Down TQt::Key_Down
#define Key_E TQt::Key_E
#define Key_eacute TQt::Key_eacute
#define Key_Eacute TQt::Key_Eacute
#define Key_ecircumflex TQt::Key_ecircumflex
#define Key_Ecircumflex TQt::Key_Ecircumflex
#define Key_ediaeresis TQt::Key_ediaeresis
#define Key_Ediaeresis TQt::Key_Ediaeresis
#define Key_egrave TQt::Key_egrave
#define Key_Egrave TQt::Key_Egrave
#define Key_End TQt::Key_End
#define Key_Enter TQt::Key_Enter
#define Key_Equal TQt::Key_Equal
#define Key_Escape TQt::Key_Escape
#define Key_eth TQt::Key_eth
#define Key_ETH TQt::Key_ETH
#define Key_Exclam TQt::Key_Exclam
#define Key_exclamdown TQt::Key_exclamdown
#define Key_F TQt::Key_F
#define Key_F1 TQt::Key_F1
#define Key_F10 TQt::Key_F10
#define Key_F11 TQt::Key_F11
#define Key_F12 TQt::Key_F12
#define Key_F13 TQt::Key_F13
#define Key_F14 TQt::Key_F14
#define Key_F15 TQt::Key_F15
#define Key_F16 TQt::Key_F16
#define Key_F17 TQt::Key_F17
#define Key_F18 TQt::Key_F18
#define Key_F19 TQt::Key_F19
#define Key_F2 TQt::Key_F2
#define Key_F20 TQt::Key_F20
#define Key_F21 TQt::Key_F21
#define Key_F22 TQt::Key_F22
#define Key_F23 TQt::Key_F23
#define Key_F24 TQt::Key_F24
#define Key_F25 TQt::Key_F25
#define Key_F26 TQt::Key_F26
#define Key_F27 TQt::Key_F27
#define Key_F28 TQt::Key_F28
#define Key_F29 TQt::Key_F29
#define Key_F3 TQt::Key_F3
#define Key_F30 TQt::Key_F30
#define Key_F31 TQt::Key_F31
#define Key_F32 TQt::Key_F32
#define Key_F33 TQt::Key_F33
#define Key_F34 TQt::Key_F34
#define Key_F35 TQt::Key_F35
#define Key_F4 TQt::Key_F4
#define Key_F5 TQt::Key_F5
#define Key_F6 TQt::Key_F6
#define Key_F7 TQt::Key_F7
#define Key_F8 TQt::Key_F8
#define Key_F9 TQt::Key_F9
#define Key_G TQt::Key_G
#define Key_Greater TQt::Key_Greater
#define Key_guillemotleft TQt::Key_guillemotleft
#define Key_guillemotright TQt::Key_guillemotright
#define Key_H TQt::Key_H
#define Key_Home TQt::Key_Home
#define Key_Hyper_L TQt::Key_Hyper_L
#define Key_Hyper_R TQt::Key_Hyper_R
#define Key_hyphen TQt::Key_hyphen
#define Key_I TQt::Key_I
#define Key_iacute TQt::Key_iacute
#define Key_Iacute TQt::Key_Iacute
#define Key_icircumflex TQt::Key_icircumflex
#define Key_Icircumflex TQt::Key_Icircumflex
#define Key_idiaeresis TQt::Key_idiaeresis
#define Key_Idiaeresis TQt::Key_Idiaeresis
#define Key_igrave TQt::Key_igrave
#define Key_Igrave TQt::Key_Igrave
#define Key_Insert TQt::Key_Insert
#define Key_J TQt::Key_J
#define Key_K TQt::Key_K
#define Key_L TQt::Key_L
#define Key_Left TQt::Key_Left
#define Key_Less TQt::Key_Less
#define Key_M TQt::Key_M
#define Key_macron TQt::Key_macron
#define Key_masculine TQt::Key_masculine
#define Key_Menu TQt::Key_Menu
#define Key_Meta TQt::Key_Meta
#define Key_Minus TQt::Key_Minus
#define Key_mu TQt::Key_mu
#define Key_multiply TQt::Key_multiply
#define Key_N TQt::Key_N
#define Key_Next TQt::Key_Next
#define Key_nobreakspace TQt::Key_nobreakspace
#define Key_notsign TQt::Key_notsign
#define Key_ntilde TQt::Key_ntilde
#define Key_Ntilde TQt::Key_Ntilde
#define Key_NumberSign TQt::Key_NumberSign
#define Key_NumLock TQt::Key_NumLock
#define Key_O TQt::Key_O
#define Key_oacute TQt::Key_oacute
#define Key_Oacute TQt::Key_Oacute
#define Key_ocircumflex TQt::Key_ocircumflex
#define Key_Ocircumflex TQt::Key_Ocircumflex
#define Key_odiaeresis TQt::Key_odiaeresis
#define Key_Odiaeresis TQt::Key_Odiaeresis
#define Key_ograve TQt::Key_ograve
#define Key_Ograve TQt::Key_Ograve
#define Key_onehalf TQt::Key_onehalf
#define Key_onequarter TQt::Key_onequarter
#define Key_onesuperior TQt::Key_onesuperior
#define Key_Ooblique TQt::Key_Ooblique
#define Key_ordfeminine TQt::Key_ordfeminine
#define Key_oslash TQt::Key_oslash
#define Key_otilde TQt::Key_otilde
#define Key_Otilde TQt::Key_Otilde
#define Key_P TQt::Key_P
#define Key_PageDown TQt::Key_PageDown
#define Key_PageUp TQt::Key_PageUp
#define Key_paragraph TQt::Key_paragraph
#define Key_ParenLeft TQt::Key_ParenLeft
#define Key_ParenRight TQt::Key_ParenRight
#define Key_Pause TQt::Key_Pause
#define Key_Percent TQt::Key_Percent
#define Key_Period TQt::Key_Period
#define Key_periodcentered TQt::Key_periodcentered
#define Key_Plus TQt::Key_Plus
#define Key_plusminus TQt::Key_plusminus
#define Key_Print TQt::Key_Print
#define Key_Prior TQt::Key_Prior
#define Key_Q TQt::Key_Q
#define Key_Question TQt::Key_Question
#define Key_questiondown TQt::Key_questiondown
#define Key_QuoteDbl TQt::Key_QuoteDbl
#define Key_QuoteLeft TQt::Key_QuoteLeft
#define Key_R TQt::Key_R
#define Key_registered TQt::Key_registered
#define Key_Return TQt::Key_Return
#define Key_Right TQt::Key_Right
#define Key_S TQt::Key_S
#define Key_ScrollLock TQt::Key_ScrollLock
#define Key_section TQt::Key_section
#define Key_Semicolon TQt::Key_Semicolon
#define Key_Shift TQt::Key_Shift
#define Key_Slash TQt::Key_Slash
#define Key_Space TQt::Key_Space
#define Key_ssharp TQt::Key_ssharp
#define Key_sterling TQt::Key_sterling
#define Key_Super_L TQt::Key_Super_L
#define Key_Super_R TQt::Key_Super_R
#define Key_SysReq TQt::Key_SysReq
#define Key_T TQt::Key_T
#define Key_Tab TQt::Key_Tab
#define Key_thorn TQt::Key_thorn
#define Key_THORN TQt::Key_THORN
#define Key_threequarters TQt::Key_threequarters
#define Key_threesuperior TQt::Key_threesuperior
#define Key_twosuperior TQt::Key_twosuperior
#define Key_U TQt::Key_U
#define Key_uacute TQt::Key_uacute
#define Key_Uacute TQt::Key_Uacute
#define Key_ucircumflex TQt::Key_ucircumflex
#define Key_Ucircumflex TQt::Key_Ucircumflex
#define Key_udiaeresis TQt::Key_udiaeresis
#define Key_Udiaeresis TQt::Key_Udiaeresis
#define Key_ugrave TQt::Key_ugrave
#define Key_Ugrave TQt::Key_Ugrave
#define Key_Underscore TQt::Key_Underscore
#define Key_unknown TQt::Key_unknown
#define Key_Up TQt::Key_Up
#define Key_V TQt::Key_V
#define Key_W TQt::Key_W
#define Key_X TQt::Key_X
#define Key_Y TQt::Key_Y
#define Key_yacute TQt::Key_yacute
#define Key_Yacute TQt::Key_Yacute
#define Key_ydiaeresis TQt::Key_ydiaeresis
#define Key_yen TQt::Key_yen
#define Key_Z TQt::Key_Z
#endif
