#ifndef QT_H
#endif /* QT_H */

#ifndef TQT_NO_CHECK
# define TQT_NO_CHECK
#endif
#define TQT_NO_PROCESS
#define TQT_NO_PALETTE
#define TQT_NO_ACTION
#ifndef TQT_NO_TEXTCODEC /* moc? */
#define TQT_NO_TEXTCODEC
#endif
#define TQT_NO_UNICODETABLES
#define TQT_NO_IMAGEIO_BMP
#define TQT_NO_IMAGEIO_PPM
#define TQT_NO_IMAGEIO_XBM
#define TQT_NO_IMAGEIO_XPM
/* #define TQT_NO_IMAGEIO_PNG //done by configure -no-png */
#define TQT_NO_ASYNC_IO
#define TQT_NO_ASYNC_IMAGE_IO
/* //#define TQT_NO_FREETYPE //done by configure -no-freetype */
#define TQT_NO_BDF
//#define TQT_NO_FONTDATABASE
#define TQT_NO_TRANSLATION
#define TQT_NO_MIME
#define TQT_NO_SOUND
/* #define TQT_NO_PROPERTIES */
#define TQT_NO_QWS_CURSOR
#define TQT_NO_CURSOR
#define TQT_NO_QWS_GFX_SPEED
#define TQT_NO_NETWORK
#define TQT_NO_COLORNAMES
#define TQT_NO_TRANSFORMATIONS
#define TQT_NO_PRINTER
#define TQT_NO_PICTURE
#define TQT_NO_LAYOUT
#define TQT_NO_DRAWUTIL
#define TQT_NO_IMAGE_TRUECOLOR
#define TQT_NO_IMAGE_SMOOTHSCALE
#define TQT_NO_IMAGE_TEXT
#define TQT_NO_DIR
#define TQT_NO_QWS_MANAGER
#define TQT_NO_TEXTSTREAM
#define TQT_NO_DATASTREAM
#define TQT_NO_QWS_SAVEFONTS
//#define TQT_NO_STRINGLIST
#define TQT_NO_TEMPLATE_VARIANT
#define TQT_NO_SESSIONMANAGER
#define TQT_NO_QWS_KEYBOARD
#define TQT_NO_SYNTAXHIGHLIGHTER

#define TQT_NO_ACCEL
#define TQT_NO_BUTTON
#define TQT_NO_DIALOG
#define TQT_NO_FRAME
#define TQT_NO_SEMIMODAL

#define TQT_NO_STYLE
#define TQT_NO_EFFECTS
#define TQT_NO_COP

#define TQT_NO_SQL

#define TQT_NO_REGEXP_CAPTURE
#define TQT_NO_REGEXP_WILDCARD

#define TQT_NO_VALIDATOR
#define TQT_NO_SPRINTF

#define TQT_NO_REGEXP

#define TQT_NO_IMAGEIO

/* #define TQT_NO_VARIANT //needed for signals/slots */

#define TQT_NO_RANGECONTROL
#define TQT_NO_QUUID_STRING
#define TQT_NO_SIGNALMAPPER

#define TQT_NO_WHEELEVENT
#define TQT_NO_BEZIER

#define TQT_NO_QWS_MOUSE_AUTO
/* #define TQT_NO_QWS_MOUSE_MANUAL */

#define TQT_NO_IMAGE_DITHER_TO_1
#define TQT_NO_IMAGE_HEURISTIC_MASK
#define TQT_NO_IMAGE_MIRROR

#ifndef TQT_NO_STL
# define TQT_NO_STL
#endif

#define TQT_NO_DATESTRING
#define TQT_NO_WMATRIX

#define TQT_NO_DIRECTPAINTER
